services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: ttn-postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ttn_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ttn-backend
    env_file:
      - ./.env
    ports:
      - "4001:4000"
    depends_on:
      - postgres
      - minio
    networks:
      - app-network

  minio:
    image: minio/minio:latest
    container_name: ttn-minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    networks:
      - app-network

  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set myminio http://minio:9000 minioadmin minioadmin;
      /usr/bin/mc mb myminio/ttn-bucket;
      /usr/bin/mc anonymous set public myminio/ttn-bucket;
      exit 0;
      "
    networks:
      - app-network

  web:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: ttn-web
    ports:
      - "3000:3000"
    env_file:
      - ./.env
    depends_on:
      - backend
      - postgres
    networks:
      - app-network

volumes:
  postgres_data:
  minio_data:

networks:
  app-network:
    driver: bridge
